# config/application.yml
defaults: &defaults
  user:
    login_expire_days: 30
    reset_password_expire_secondes: 600

development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults