development:
  adapter: postgis
  encoding: utf8
  database: smarto_development
  pool: 5
  username: postgres
  password: 123456
  host: localhost
  port: 5432

test:
  adapter: postgis
  encoding: utf8
  database: smarto_test
  pool: 5
  username: postgres
  password: 123456
  host: localhost
  port: 5432
production:
  adapter: postgis
  encoding: utf8
  database: smarto_production
  pool: 5 
  username: postgres
  password: 123456
  host: localhost
  port: 5432