# config/application.yml
defaults: &defaults
  weather_cn:
    url: "http://open.weather.com.cn/data/"
    app_id: "e670784a4724e520"
    app_id_param: "e67078"
    private_key: <%= ENV['WEATHER_CN_SECRET_KEY']%>
    cache_peroid: 1800
  etouch:
    url: "http://wthrcdn.etouch.cn/WeatherApi?citykey="
    cache_peroid: 3600

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
